### ISSUE TITLE
quest 6403 can not complete

### ISSUE THREAD

**Issue by H0zen** [H0zen/mangos-issues#30]
_From @mpfans on May 7, 2016 22:11_

quest name 'The Great Masquerade' ,quest accepted

reginald windsor not move 

error message:

Entry -3000106 not found but requested

_Copied from original issue: H0zen/M0-server#30_

**Comment by mpfans** [comment]
fixed https://github.com/mangoszero/server/commit/77876df7087d6870ba5408cd67ad830c659dfe73
