### ISSUE TITLE
Hunter pet BUG 

### ISSUE THREAD

**Issue by mpfans** [H0zen/mangos-issues#48]
When you  cast 'dismiss pet',then cast 'Tame beast',Then your pet will disappear and you will get a new pet. 

That's not true,  Right way is you  cast 'dismiss pet',then cast 'Tame beast',it will remind you that you have a pet.

**Comment by mpfans** [comment]
If your pet is dead, you can cast 'Tame beast'cast

**Comment by H0zen** [comment]
Fixed with https://github.com/mangoszero/server/pull/135
