### ISSUE TITLE
Warrior's bug

### ISSUE THREAD

**Issue by mpfans** [H0zen/mangos-issues#52]
player 1 = A
player 2 = B

A cast 'Battle Shout(RANK =1)' ,B cast 'Battle Shout(RANK=2)', then A and B also owned 'Battle Shout' rank 1 and rank 2 buff

**Comment by mpfans** [comment]
![20160613112432](https://cloud.githubusercontent.com/assets/18187177/15996379/780d64da-3159-11e6-99c3-62e1417c38c9.png)

**Comment by H0zen** [comment]
Fixed with https://github.com/mangoszero/server/pull/141/
